### ISSUE TITLE
在你的train.py文件中，发现你用了多gpu训练

### ISSUE THREAD

**Issue by gittigxuy** [Jeremyczhj/FashionAI_Tianchi_2018#2]
![image](https://user-images.githubusercontent.com/15090557/44916844-4a07da00-ad69-11e8-9e1c-69602ee7302d.png)
如果我只有1块gpu的话，那我应该怎么改呢？仅仅将gpus这个参数改为1就好了吗？
multi_gpu_model(model, gpus=1)

**Comment by Jeremyczhj** [comment]
> ![image](https://user-images.githubusercontent.com/15090557/44916844-4a07da00-ad69-11e8-9e1c-69602ee7302d.png)
> 如果我只有1块gpu的话，那我应该怎么改呢？仅仅将gpus这个参数改为1就好了吗？
> multi_gpu_model(model, gpus=1)

去掉model2 = multi_gpu_model(model, 2)这一句，然后把下面的model2全改成model就好
