### ISSUE TITLE
about model

### ISSUE THREAD

**Issue by BackT0TheFuture** [Jeremyczhj/FashionAI_Tianchi_2018#3]
Hi,there
thanks for your great works,
recently I'm learning deep learning courses,
but due to my gpu is  powerless , I wanna do fine-tune based on your models,
would  you like to share the model files you trained?
thanks!

**Comment by Jeremyczhj** [comment]
> Hi,there
> thanks for your great works,
> recently I'm learning deep learning courses,
> but due to my gpu is powerless , I wanna do fine-tune based on your models,
> would you like to share the model files you trained?
> thanks!

Oh, sorry,
I have deleted my model files already. 
you can use pre-trained models from keras as well.

**Comment by BackT0TheFuture** [comment]
got it , thanks
